### ISSUE TITLE
e-ORDER link in navbar

### ISSUE THREAD

**Issue by McDevil96** [rallisf1/exercise#1]
Στο navbar μας, το link e-ORDER είναι με κόκκινο background, έτσι πρέπει να είναι όταν κάνεις **hover** σε οποιοδήποτε link του navbar ή μόνο αυτό πρέπει να είναι ξεχωριστό ??

**Comment by rallisf1** [comment]
Ξεχωριστό, ένα button ουσιαστικά δίπλα από τη λίστα του μενού. Υπάρχουν δεκάδες τρόποι να γίνει χωρίς απαραίτητα κάποιος να είναι πιο σωστός από τον άλλο.
